name: Build on multiple platforms
on: [push, pull_request]

jobs:
  build-matrix:
    name: Dub builds linux, macos
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        dc: [dmd-latest, ldc-latest]
        exclude:
          - { os: macOs-latest, dc: dmd-latest }
      

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Build
        run: make
      